version: '3'
services:
  mysql:
    build: ../mysql
    environment:
        MYSQL_ROOT_PASSWORD: admin
    ports:
        - 3306:3306

  phpmyadmin:
    build: ../phpmyadmin
    ports:
        - 6060:80
    environment:
        MYSQL_ROOT_PASSWORD: admin
    links:
        - mysql:db
    
  wildfly:
    build: ../wildfly
    ports:
     - "9090:8080"
     - "9990:9990"
     - "8787:8787"
     

